// Generated by scripts/gen-locale-routes.mjs; do not edit.
// Re-exports src/app/(docs)/responsible-use/page.tsx under each language prefix.
export { default, metadata } from '@/app/(docs)/responsible-use/page'
