// The countries and territories the site names and the home page map counts
// ("Where journals are published"): the editors' list of 219 places, with
// their English and Chinese names, kind and continent, plus two UN member
// states it left out (North Korea, Comoros). The English names here are the
// site's country names (countryDisplayName). A dependent territory off the
// list is counted under the country that administers it (PARENT).

export type PlaceKind = 'state' | 'observer' | 'disputed' | 'territory' | 'associated'
export type Continent = 'Asia' | 'Europe' | 'Africa' | 'North America' | 'South America' | 'Oceania'

export interface ListedPlace { code: string; name: string; zh: string; kind: PlaceKind; continent: Continent }

const ROWS: [code: string, name: string, zh: string, kind: PlaceKind, continent: Continent][] = [
  ['CN', 'China', '中国', 'state', 'Asia'],
  ['JP', 'Japan', '日本', 'state', 'Asia'],
  ['KR', 'South Korea', '韩国', 'state', 'Asia'],
  ['IN', 'India', '印度', 'state', 'Asia'],
  ['ID', 'Indonesia', '印度尼西亚', 'state', 'Asia'],
  ['VN', 'Vietnam', '越南', 'state', 'Asia'],
  ['TH', 'Thailand', '泰国', 'state', 'Asia'],
  ['PH', 'Philippines', '菲律宾', 'state', 'Asia'],
  ['MY', 'Malaysia', '马来西亚', 'state', 'Asia'],
  ['SG', 'Singapore', '新加坡', 'state', 'Asia'],
  ['PK', 'Pakistan', '巴基斯坦', 'state', 'Asia'],
  ['BD', 'Bangladesh', '孟加拉国', 'state', 'Asia'],
  ['LK', 'Sri Lanka', '斯里兰卡', 'state', 'Asia'],
  ['MV', 'Maldives', '马尔代夫', 'state', 'Asia'],
  ['NP', 'Nepal', '尼泊尔', 'state', 'Asia'],
  ['BT', 'Bhutan', '不丹', 'state', 'Asia'],
  ['MM', 'Myanmar', '缅甸', 'state', 'Asia'],
  ['KH', 'Cambodia', '柬埔寨', 'state', 'Asia'],
  ['LA', 'Laos', '老挝', 'state', 'Asia'],
  ['BN', 'Brunei', '文莱', 'state', 'Asia'],
  ['TL', 'Timor-Leste', '东帝汶', 'state', 'Asia'],
  ['KP', 'North Korea', '朝鲜', 'state', 'Asia'],
  ['MN', 'Mongolia', '蒙古', 'state', 'Asia'],
  ['KZ', 'Kazakhstan', '哈萨克斯坦', 'state', 'Asia'],
  ['UZ', 'Uzbekistan', '乌兹别克斯坦', 'state', 'Asia'],
  ['TM', 'Turkmenistan', '土库曼斯坦', 'state', 'Asia'],
  ['KG', 'Kyrgyzstan', '吉尔吉斯斯坦', 'state', 'Asia'],
  ['TJ', 'Tajikistan', '塔吉克斯坦', 'state', 'Asia'],
  ['AF', 'Afghanistan', '阿富汗', 'state', 'Asia'],
  ['IR', 'Iran', '伊朗', 'state', 'Asia'],
  ['IQ', 'Iraq', '伊拉克', 'state', 'Asia'],
  ['SA', 'Saudi Arabia', '沙特阿拉伯', 'state', 'Asia'],
  ['AE', 'UAE', '阿拉伯联合酋长国', 'state', 'Asia'],
  ['QA', 'Qatar', '卡塔尔', 'state', 'Asia'],
  ['KW', 'Kuwait', '科威特', 'state', 'Asia'],
  ['OM', 'Oman', '阿曼', 'state', 'Asia'],
  ['YE', 'Yemen', '叶门', 'state', 'Asia'],
  ['BH', 'Bahrain', '巴林', 'state', 'Asia'],
  ['IL', 'Israel', '以色列', 'state', 'Asia'],
  ['PS', 'Palestine', '巴勒斯坦', 'observer', 'Asia'],
  ['JO', 'Jordan', '约旦', 'state', 'Asia'],
  ['LB', 'Lebanon', '黎巴嫩', 'state', 'Asia'],
  ['SY', 'Syria', '叙利亚', 'state', 'Asia'],
  ['TR', 'Turkey', '土耳其', 'state', 'Asia'],
  ['CY', 'Cyprus', '塞浦路斯', 'state', 'Asia'],
  ['AZ', 'Azerbaijan', '阿塞拜疆', 'state', 'Asia'],
  ['GE', 'Georgia', '格鲁吉亚', 'state', 'Asia'],
  ['AM', 'Armenia', '亚美尼亚', 'state', 'Asia'],
  ['HK', 'Hong Kong', '中国香港', 'territory', 'Asia'],
  ['MO', 'Macao', '中国澳门', 'territory', 'Asia'],
  ['TW', 'Taiwan', '中国台湾', 'territory', 'Asia'],
  ['RU', 'Russia', '俄罗斯', 'state', 'Europe'],
  ['GB', 'United Kingdom', '英国', 'state', 'Europe'],
  ['FR', 'France', '法国', 'state', 'Europe'],
  ['DE', 'Germany', '德国', 'state', 'Europe'],
  ['IT', 'Italy', '意大利', 'state', 'Europe'],
  ['ES', 'Spain', '西班牙', 'state', 'Europe'],
  ['PT', 'Portugal', '葡萄牙', 'state', 'Europe'],
  ['NL', 'Netherlands', '荷兰', 'state', 'Europe'],
  ['BE', 'Belgium', '比利时', 'state', 'Europe'],
  ['LU', 'Luxembourg', '卢森堡', 'state', 'Europe'],
  ['CH', 'Switzerland', '瑞士', 'state', 'Europe'],
  ['AT', 'Austria', '奥地利', 'state', 'Europe'],
  ['IE', 'Ireland', '爱尔兰', 'state', 'Europe'],
  ['GR', 'Greece', '希腊', 'state', 'Europe'],
  ['DK', 'Denmark', '丹麦', 'state', 'Europe'],
  ['NO', 'Norway', '挪威', 'state', 'Europe'],
  ['SE', 'Sweden', '瑞典', 'state', 'Europe'],
  ['FI', 'Finland', '芬兰', 'state', 'Europe'],
  ['IS', 'Iceland', '冰岛', 'state', 'Europe'],
  ['PL', 'Poland', '波兰', 'state', 'Europe'],
  ['CZ', 'Czechia', '捷克', 'state', 'Europe'],
  ['SK', 'Slovakia', '斯洛伐克', 'state', 'Europe'],
  ['HU', 'Hungary', '匈牙利', 'state', 'Europe'],
  ['UA', 'Ukraine', '乌克兰', 'state', 'Europe'],
  ['BY', 'Belarus', '白俄罗斯', 'state', 'Europe'],
  ['RO', 'Romania', '罗马尼亚', 'state', 'Europe'],
  ['BG', 'Bulgaria', '保加利亚', 'state', 'Europe'],
  ['RS', 'Serbia', '塞尔维亚', 'state', 'Europe'],
  ['HR', 'Croatia', '克罗地亚', 'state', 'Europe'],
  ['SI', 'Slovenia', '斯洛文尼亚', 'state', 'Europe'],
  ['BA', 'Bosnia and Herzegovina', '波斯尼亚和黑塞哥维那', 'state', 'Europe'],
  ['ME', 'Montenegro', '黑山', 'state', 'Europe'],
  ['MK', 'North Macedonia', '北马其顿', 'state', 'Europe'],
  ['AL', 'Albania', '阿尔巴尼亚', 'state', 'Europe'],
  ['EE', 'Estonia', '爱沙尼亚', 'state', 'Europe'],
  ['LV', 'Latvia', '拉脱维亚', 'state', 'Europe'],
  ['LT', 'Lithuania', '立陶宛', 'state', 'Europe'],
  ['MD', 'Moldova', '摩尔多瓦', 'state', 'Europe'],
  ['MT', 'Malta', '马耳他', 'state', 'Europe'],
  ['AD', 'Andorra', '安道尔', 'state', 'Europe'],
  ['MC', 'Monaco', '摩纳哥', 'state', 'Europe'],
  ['SM', 'San Marino', '圣马力诺', 'state', 'Europe'],
  ['LI', 'Liechtenstein', '列支敦士登', 'state', 'Europe'],
  ['VA', 'Vatican City', '梵蒂冈', 'observer', 'Europe'],
  ['XK', 'Kosovo', '科索沃', 'disputed', 'Europe'],
  ['GI', 'Gibraltar', '直布罗陀', 'territory', 'Europe'],
  ['FO', 'Faroe Islands', '法罗群岛', 'territory', 'Europe'],
  ['GL', 'Greenland', '格陵兰', 'territory', 'Europe'],
  ['IM', 'Isle of Man', '马恩岛', 'territory', 'Europe'],
  ['JE', 'Jersey', '泽西岛', 'territory', 'Europe'],
  ['GG', 'Guernsey', '根西岛', 'territory', 'Europe'],
  ['EG', 'Egypt', '埃及', 'state', 'Africa'],
  ['ZA', 'South Africa', '南非', 'state', 'Africa'],
  ['NG', 'Nigeria', '尼日利亚', 'state', 'Africa'],
  ['DZ', 'Algeria', '阿尔及利亚', 'state', 'Africa'],
  ['MA', 'Morocco', '摩洛哥', 'state', 'Africa'],
  ['ET', 'Ethiopia', '埃塞俄比亚', 'state', 'Africa'],
  ['KE', 'Kenya', '肯尼亚', 'state', 'Africa'],
  ['TZ', 'Tanzania', '坦桑尼亚', 'state', 'Africa'],
  ['UG', 'Uganda', '乌干达', 'state', 'Africa'],
  ['GH', 'Ghana', '加纳', 'state', 'Africa'],
  ['AO', 'Angola', '安哥拉', 'state', 'Africa'],
  ['TN', 'Tunisia', '突尼斯', 'state', 'Africa'],
  ['LY', 'Libya', '利比亚', 'state', 'Africa'],
  ['SD', 'Sudan', '苏丹', 'state', 'Africa'],
  ['SS', 'South Sudan', '南苏丹', 'state', 'Africa'],
  ['CD', 'DR Congo', '刚果民主共和国', 'state', 'Africa'],
  ['CG', 'Republic of the Congo', '刚果共和国', 'state', 'Africa'],
  ['CM', 'Cameroon', '喀麦隆', 'state', 'Africa'],
  ['CI', 'Ivory Coast', '科特迪瓦', 'state', 'Africa'],
  ['SN', 'Senegal', '塞内加尔', 'state', 'Africa'],
  ['KM', 'Comoros', '科摩罗', 'state', 'Africa'],
  ['MG', 'Madagascar', '马达加斯加', 'state', 'Africa'],
  ['MU', 'Mauritius', '毛里求斯', 'state', 'Africa'],
  ['SC', 'Seychelles', '塞舌尔', 'state', 'Africa'],
  ['NA', 'Namibia', '纳米比亚', 'state', 'Africa'],
  ['BW', 'Botswana', '博茨瓦纳', 'state', 'Africa'],
  ['ZW', 'Zimbabwe', '津巴布韦', 'state', 'Africa'],
  ['ZM', 'Zambia', '赞比亚', 'state', 'Africa'],
  ['MW', 'Malawi', '马拉维', 'state', 'Africa'],
  ['MZ', 'Mozambique', '莫桑比克', 'state', 'Africa'],
  ['RW', 'Rwanda', '卢旺达', 'state', 'Africa'],
  ['BI', 'Burundi', '布隆迪', 'state', 'Africa'],
  ['SO', 'Somalia', '索马里', 'state', 'Africa'],
  ['DJ', 'Djibouti', '吉布提', 'state', 'Africa'],
  ['ER', 'Eritrea', '厄立特里亚', 'state', 'Africa'],
  ['ML', 'Mali', '马里', 'state', 'Africa'],
  ['BF', 'Burkina Faso', '布基纳法索', 'state', 'Africa'],
  ['NE', 'Niger', '尼日尔', 'state', 'Africa'],
  ['TD', 'Chad', '乍得', 'state', 'Africa'],
  ['CF', 'Central African Republic', '中非共和国', 'state', 'Africa'],
  ['GA', 'Gabon', '加蓬', 'state', 'Africa'],
  ['GQ', 'Equatorial Guinea', '赤道几内亚', 'state', 'Africa'],
  ['ST', 'Sao Tome and Principe', '圣多美和普林西比', 'state', 'Africa'],
  ['CV', 'Cape Verde', '佛得角', 'state', 'Africa'],
  ['GN', 'Guinea', '几内亚', 'state', 'Africa'],
  ['GW', 'Guinea-Bissau', '几内亚比绍', 'state', 'Africa'],
  ['SL', 'Sierra Leone', '塞拉利昂', 'state', 'Africa'],
  ['LR', 'Liberia', '利比里亚', 'state', 'Africa'],
  ['TG', 'Togo', '多哥', 'state', 'Africa'],
  ['BJ', 'Benin', '贝宁', 'state', 'Africa'],
  ['MR', 'Mauritania', '毛里塔尼亚', 'state', 'Africa'],
  ['GM', 'Gambia', '冈比亚', 'state', 'Africa'],
  ['LS', 'Lesotho', '莱索托', 'state', 'Africa'],
  ['SZ', 'Eswatini', '斯威士兰', 'state', 'Africa'],
  ['EH', 'Western Sahara', '西撒哈拉', 'disputed', 'Africa'],
  ['RE', 'Reunion', '留尼汪', 'territory', 'Africa'],
  ['US', 'United States', '美国', 'state', 'North America'],
  ['CA', 'Canada', '加拿大', 'state', 'North America'],
  ['MX', 'Mexico', '墨西哥', 'state', 'North America'],
  ['CU', 'Cuba', '古巴', 'state', 'North America'],
  ['JM', 'Jamaica', '牙买加', 'state', 'North America'],
  ['HT', 'Haiti', '海地', 'state', 'North America'],
  ['DO', 'Dominican Republic', '多米尼加共和国', 'state', 'North America'],
  ['GT', 'Guatemala', '危地马拉', 'state', 'North America'],
  ['BZ', 'Belize', '伯利兹', 'state', 'North America'],
  ['SV', 'El Salvador', '萨尔瓦多', 'state', 'North America'],
  ['HN', 'Honduras', '洪都拉斯', 'state', 'North America'],
  ['NI', 'Nicaragua', '尼加拉瓜', 'state', 'North America'],
  ['CR', 'Costa Rica', '哥斯达黎加', 'state', 'North America'],
  ['PA', 'Panama', '巴拿马', 'state', 'North America'],
  ['BS', 'Bahamas', '巴哈马', 'state', 'North America'],
  ['BB', 'Barbados', '巴巴多斯', 'state', 'North America'],
  ['AG', 'Antigua and Barbuda', '安提瓜和巴布达', 'state', 'North America'],
  ['KN', 'St. Kitts and Nevis', '圣基茨和尼维斯', 'state', 'North America'],
  ['DM', 'Dominica', '多米尼克', 'state', 'North America'],
  ['LC', 'St. Lucia', '圣卢西亚', 'state', 'North America'],
  ['VC', 'St. Vincent', '圣文森特和格林纳丁斯', 'state', 'North America'],
  ['GD', 'Grenada', '格林纳达', 'state', 'North America'],
  ['TT', 'Trinidad and Tobago', '特立尼达和多巴哥', 'state', 'North America'],
  ['PR', 'Puerto Rico', '波多黎各', 'territory', 'North America'],
  ['VI', 'US Virgin Islands', '美属维尔京群岛', 'territory', 'North America'],
  ['VG', 'British Virgin Islands', '英属维尔京群岛', 'territory', 'North America'],
  ['KY', 'Cayman Islands', '开曼群岛', 'territory', 'North America'],
  ['BM', 'Bermuda', '百慕大', 'territory', 'North America'],
  ['AW', 'Aruba', '阿鲁巴', 'territory', 'North America'],
  ['BR', 'Brazil', '巴西', 'state', 'South America'],
  ['AR', 'Argentina', '阿根廷', 'state', 'South America'],
  ['CO', 'Colombia', '哥伦比亚', 'state', 'South America'],
  ['PE', 'Peru', '秘鲁', 'state', 'South America'],
  ['VE', 'Venezuela', '委内瑞拉', 'state', 'South America'],
  ['CL', 'Chile', '智利', 'state', 'South America'],
  ['EC', 'Ecuador', '厄瓜多尔', 'state', 'South America'],
  ['BO', 'Bolivia', '玻利维亚', 'state', 'South America'],
  ['UY', 'Uruguay', '乌拉圭', 'state', 'South America'],
  ['PY', 'Paraguay', '巴拉圭', 'state', 'South America'],
  ['GY', 'Guyana', '圭亚那', 'state', 'South America'],
  ['SR', 'Suriname', '苏里南', 'state', 'South America'],
  ['GF', 'French Guiana', '法属圭亚那', 'territory', 'South America'],
  ['FK', 'Falkland Islands', '马尔维纳斯群岛(福克兰)', 'territory', 'South America'],
  ['AU', 'Australia', '澳大利亚', 'state', 'Oceania'],
  ['NZ', 'New Zealand', '新西兰', 'state', 'Oceania'],
  ['PG', 'Papua New Guinea', '巴布亚新几内亚', 'state', 'Oceania'],
  ['FJ', 'Fiji', '斐济', 'state', 'Oceania'],
  ['SB', 'Solomon Islands', '所罗门群岛', 'state', 'Oceania'],
  ['VU', 'Vanuatu', '瓦努阿图', 'state', 'Oceania'],
  ['WS', 'Samoa', '萨摩亚', 'state', 'Oceania'],
  ['TO', 'Tonga', '汤加', 'state', 'Oceania'],
  ['KI', 'Kiribati', '基里巴斯', 'state', 'Oceania'],
  ['FM', 'Micronesia', '密克罗尼西亚联邦', 'state', 'Oceania'],
  ['MH', 'Marshall Islands', '马绍尔群岛', 'state', 'Oceania'],
  ['PW', 'Palau', '帕劳', 'state', 'Oceania'],
  ['TV', 'Tuvalu', '图瓦卢', 'state', 'Oceania'],
  ['NR', 'Nauru', '瑙鲁', 'state', 'Oceania'],
  ['CK', 'Cook Islands', '库克群岛', 'associated', 'Oceania'],
  ['NU', 'Niue', '纽埃', 'associated', 'Oceania'],
  ['GU', 'Guam', '关岛', 'territory', 'Oceania'],
  ['NC', 'New Caledonia', '新喀里多尼亚', 'territory', 'Oceania'],
  ['PF', 'French Polynesia', '法属波利尼西亚', 'territory', 'Oceania'],
  ['AS', 'American Samoa', '美属萨摩亚', 'territory', 'Oceania'],
]

/** Listed places by ISO 3166-1 alpha-2 code (XK for Kosovo). */
export const LISTED_PLACES: ReadonlyMap<string, ListedPlace> = new Map(
  ROWS.map(([code, name, zh, kind, continent]) => [code, { code, name, zh, kind, continent }]),
)

/** Territories off the list, by the listed country that administers them. */
export const PARENT: Readonly<Record<string, string>> = {
  // France
  GP: 'FR', MQ: 'FR', YT: 'FR', PM: 'FR', WF: 'FR', MF: 'FR', BL: 'FR', TF: 'FR',
  // United Kingdom
  AI: 'GB', MS: 'GB', TC: 'GB', SH: 'GB', PN: 'GB', IO: 'GB', GS: 'GB',
  // Netherlands
  CW: 'NL', SX: 'NL', BQ: 'NL',
  // United States
  MP: 'US', UM: 'US',
  // Australia
  NF: 'AU', CX: 'AU', CC: 'AU', HM: 'AU',
  // others
  AX: 'FI', SJ: 'NO', BV: 'NO', TK: 'NZ',
}

/** The listed place a country code is counted under: itself, its administering country, or null. */
export function listedPlaceOf(code: string | null | undefined): ListedPlace | null {
  if (!code) return null
  return LISTED_PLACES.get(code) ?? LISTED_PLACES.get(PARENT[code] ?? '') ?? null
}
