import type { Journal, PqfScore, PlatformStats } from './types'

// PQF v1.0 formula: JTF/25 + MQF/25 + EGF/20 + TDF/15 + CVF/10 + RIF/5 = 100
function pqf(jtf: number, mqf: number, egf: number, tdf: number, cvf: number, rif: number): PqfScore {
  const total = jtf + mqf + egf + tdf + cvf + rif
  const grade =
    total >= 90 ? 'A+' :
    total >= 80 ? 'A'  :
    total >= 70 ? 'B+' :
    total >= 60 ? 'B'  :
    total >= 50 ? 'C'  :
    total >= 40 ? 'D'  : 'E'
  return {
    total,
    grade,
    subfactors: { jtf, mqf, egf, tdf, cvf, rif },
    evaluated_at: '2026-06-22',
    version: 'PQF v1.0',
  }
}

const COVER = (name: string) => `https://panorama-sg.com/QKFM/${name}.png`

// ── PSG Journals (12 journals published by Panorama Scholarly Group) ──────
// Publisher: Panorama Scholarly Group, Berlin, Germany
// ISSN registration: Germany (via ISSN International Centre)
// Real PQF assessed 2026-06-22 against live journal websites
export const PSG_JOURNALS: Journal[] = [
  {
    id: 'j-grhas',
    journal_code: 'grhas',
    title: 'Global Review of Humanities, Arts, and Society',
    short_title: 'GRHAS',
    issn_print: null,
    issn_online: '3052-539X',
    publisher: 'Panorama Scholarly Group',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Bimonthly',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/files',
    cover_image_url: COVER('GRAHS'),
    oai_base_url: 'https://journals.panorama-sg.com/index.php/files/oai',
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 64,
    transparency_score: 76,
    indexing_readiness: 'B',
    // APC $450 disclosed; CC BY 4.0; ORCID required from authors; 18-member board; OAI-PMH active; COPE
    pqf: pqf(19, 16, 12, 11, 4, 4),  // total: 66, Grade B
    article_count: 24,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-afs',
    journal_code: 'afs',
    title: 'AI & Future Society',
    short_title: 'AFS',
    issn_print: null,
    issn_online: '3053-4011',
    publisher: 'Panorama Scholarly Group',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Biannual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/afs',
    cover_image_url: COVER('AFS'),
    oai_base_url: 'https://journals.panorama-sg.com/index.php/AFS/oai',
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 56,
    transparency_score: 64,
    indexing_readiness: 'B',
    // CC BY 4.0; COPE; APC page exists (amount not published); Crossref DOI
    pqf: pqf(16, 14, 11, 9, 3, 3),  // total: 56, Grade C
    article_count: 18,
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-jlpcs',
    journal_code: 'jlpcs',
    title: 'Journal of Law, Psychology, and Communication Studies',
    short_title: 'JLPCS',
    issn_print: null,
    issn_online: '3052-9654',
    publisher: 'Panorama Scholarly Group',
    country: 'China, Hong Kong SAR',
    language: 'English; Chinese',
    frequency: 'Biannual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/jlpcs',
    cover_image_url: COVER('JLPCS'),
    oai_base_url: 'https://journals.panorama-sg.com/index.php/jlpcs/oai',
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 60,
    transparency_score: 60,
    indexing_readiness: 'C',
    // CC BY 4.0; OAI-PMH confirmed; COPE; double-blind; plagiarism + data policies; Crossref DOI
    pqf: pqf(15, 15, 11, 11, 4, 3),  // total: 59, Grade C
    article_count: 20,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-hnex',
    journal_code: 'hnex',
    title: 'Health Nexus: Interdisciplinary Medical Research Journal',
    short_title: 'Health Nexus',
    issn_print: null,
    issn_online: '3053-7037',
    publisher: 'Panorama Scholarly Group',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Annual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/HealthNexus',
    cover_image_url: COVER('HealthNexus'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 52,
    transparency_score: 64,
    indexing_readiness: 'C',
    // CC BY 4.0; COPE; medical ethics requirement; annual frequency limits metadata volume
    pqf: pqf(16, 13, 11, 9, 3, 4),  // total: 56, Grade C
    article_count: 15,
    created_at: '2024-09-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-pear',
    journal_code: 'pear',
    title: 'PoliEcoM Administration Review',
    short_title: 'PEMR',
    issn_print: null,
    issn_online: '3053-3597',
    publisher: 'Panorama Scholarly Group',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Biannual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/pemr',
    cover_image_url: COVER('REMR'),
    oai_base_url: 'https://journals.panorama-sg.com/index.php/pemr/oai',
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 56,
    transparency_score: 64,
    indexing_readiness: 'B',
    // CC BY 4.0; double-blind; OAI-PMH confirmed; COPE; plagiarism policy; Crossref DOI
    pqf: pqf(16, 14, 12, 12, 4, 3),  // total: 61, Grade B
    article_count: 12,
    created_at: '2024-09-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-jesa',
    journal_code: 'jesa',
    title: 'Journal of Engineering Systems and Applications',
    short_title: 'JESA',
    issn_print: null,
    issn_online: '3053-478X',
    publisher: 'Panorama Scholarly Group',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Annual',
    open_access: true,
    license: 'CC BY-NC 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/jesa',
    cover_image_url: COVER('JESA'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 52,
    transparency_score: 56,
    indexing_readiness: 'C',
    // CC BY-NC 4.0 (non-commercial restricts DOAJ eligibility); double-blind; annual
    pqf: pqf(14, 13, 11, 9, 3, 3),  // total: 53, Grade C
    article_count: 11,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-tts',
    journal_code: 'tts',
    title: 'Three Teachings Studies: Confucianism, Daoism, and Buddhism',
    short_title: 'TTS',
    issn_print: null,
    issn_online: '3053-6553',
    publisher: 'Panorama Scholarly Group',
    country: 'China, Hong Kong SAR',
    language: 'English; Chinese; Japanese; Korean; Vietnamese',
    frequency: 'Annual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/tts',
    cover_image_url: COVER('TTS'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'application_submitted',
    openalex_source_id: null,
    metadata_quality_score: 52,
    transparency_score: 60,
    indexing_readiness: 'C',
    // CC BY 4.0; DOAJ application submitted; 6-member board (no ORCID); multilingual metadata
    pqf: pqf(15, 13, 9, 9, 3, 3),  // total: 52, Grade C
    article_count: 8,
    created_at: '2024-12-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-rggd',
    journal_code: 'rggd',
    title: 'Rural Governance and Green Development',
    short_title: 'RGGD',
    issn_print: null,
    issn_online: '3053-7282',
    publisher: 'Panorama Scholarly Group',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Annual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/rggd',
    cover_image_url: COVER('RGGD'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 48,
    transparency_score: 60,
    indexing_readiness: 'C',
    // CC BY 4.0; COPE; plagiarism policy; annual publication; limited board disclosure
    pqf: pqf(15, 12, 10, 9, 3, 3),  // total: 52, Grade C
    article_count: 8,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-rjgms',
    journal_code: 'rjgms',
    title: 'Resonance: Journal of Global Music Studies',
    short_title: 'Resonance',
    issn_print: null,
    issn_online: '3053-4410',
    publisher: 'Panorama Scholarly Group',
    country: 'China, Hong Kong SAR',
    language: 'English; Chinese; German; Italian; Russian',
    frequency: 'Biannual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/Resonance',
    cover_image_url: COVER('RESONANCE'),
    oai_base_url: 'https://journals.panorama-sg.com/index.php/Resonance/oai',
    registration_country: 'Germany',
    doaj_status: 'application_submitted',
    openalex_source_id: 'S5407051440',
    metadata_quality_score: 64,
    transparency_score: 68,
    indexing_readiness: 'B',
    // OpenAlex indexed (S5407051440); OAI-PMH active; 13-member board (2 ORCID); DOAJ applied; fieldwork ethics policy
    pqf: pqf(17, 16, 15, 13, 5, 4),  // total: 70, Grade B+
    article_count: 14,
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-csgs',
    journal_code: 'csgs',
    title: 'Climate Sustainability & Global Systems',
    short_title: 'CSGS',
    issn_print: null,
    issn_online: '3054-9663',
    publisher: 'Panorama Scholarly Group',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Quarterly',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/csgs',
    cover_image_url: COVER('CSGS'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 48,
    transparency_score: 72,
    indexing_readiness: 'B',
    // APC $500 explicitly disclosed; all articles assigned DOIs; double-blind; AI transparency policy; quarterly
    pqf: pqf(18, 12, 11, 11, 5, 4),  // total: 61, Grade B
    article_count: 6,
    created_at: '2025-06-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-jscc',
    journal_code: 'jscc',
    title: 'Journal of Social Cognition and Communication',
    short_title: 'JSCC',
    issn_print: null,
    issn_online: '3054-6958',
    publisher: 'Panorama Scholarly Group',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Biannual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/jscc',
    cover_image_url: COVER('JSCC'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 56,
    transparency_score: 64,
    indexing_readiness: 'C',
    // CC BY 4.0; double-anonymous peer review; Crossref DOI confirmed; COPE; plagiarism policy
    pqf: pqf(16, 14, 12, 9, 4, 3),  // total: 58, Grade C
    article_count: 10,
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-silence',
    journal_code: 'silence',
    title: 'Silence',
    short_title: 'Silence',
    issn_print: null,
    issn_online: '3054-4386',
    publisher: 'Panorama Scholarly Group',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Irregular',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Peer review',
    website_url: 'https://journals.panorama-sg.com/index.php/Silence',
    cover_image_url: COVER('Silence'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 48,
    transparency_score: 56,
    indexing_readiness: 'C',
    // CC BY 4.0; Crossref DOI confirmed; COPE; experimental/irregular format limits TDF/CVF
    pqf: pqf(14, 12, 10, 9, 3, 3),  // total: 51, Grade C
    article_count: 5,
    created_at: '2025-06-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
]

// ── Indexed Journals (third-party publishers indexed by POSI) ─────────────
export const INDEXED_JOURNALS: Journal[] = [
  {
    id: 'j-jmss',
    journal_code: 'jmss',
    title: 'Journal of Modern Social Sciences',
    short_title: 'JMSS',
    issn_print: '3078-4433',
    issn_online: '3078-4441',
    publisher: 'Asia Technology Research Institute',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Continuous',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://atripress.org/index.php/jmss',
    cover_image_url: 'https://atripress.org/public/journals/1/cover_issue_5_en_US.jpg',
    oai_base_url: null,
    registration_country: 'China, Hong Kong SAR',
    doaj_status: null,
    openalex_source_id: null,
    metadata_quality_score: 60,
    transparency_score: 65,
    indexing_readiness: 'C',
    pqf: pqf(17, 14, 11, 10, 2, 2),  // total: 56, Grade C
    article_count: 0,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-jcsis',
    journal_code: 'jcsis',
    title: 'Journal of Current Social Issues Studies',
    short_title: 'JCSIS',
    issn_print: '3078-5316',
    issn_online: '3078-5324',
    publisher: 'Asia Technology Research Institute',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Continuous',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://atripress.org/index.php/jcsis',
    cover_image_url: 'https://atripress.org/public/journals/2/cover_issue_6_en_US.jpg',
    oai_base_url: null,
    registration_country: 'China, Hong Kong SAR',
    doaj_status: null,
    openalex_source_id: null,
    metadata_quality_score: 63,
    transparency_score: 68,
    indexing_readiness: 'B',
    pqf: pqf(18, 15, 14, 10, 2, 2),  // total: 61, Grade B
    article_count: 0,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-jcac',
    journal_code: 'jcac',
    title: 'Journal of Contemporary Art Criticism',
    short_title: 'JCAC',
    issn_print: '3079-7470',
    issn_online: '3079-7489',
    publisher: 'Asia Technology Research Institute',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Continuous',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://atripress.org/index.php/jcac',
    cover_image_url: 'https://atripress.org/public/journals/4/cover_issue_9_en_US.jpg',
    oai_base_url: null,
    registration_country: 'China, Hong Kong SAR',
    doaj_status: null,
    openalex_source_id: null,
    metadata_quality_score: 58,
    transparency_score: 63,
    indexing_readiness: 'C',
    pqf: pqf(14, 12, 10, 9, 2, 1),  // total: 48, Grade D
    article_count: 0,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
]

// ── SHIHARR Journals (ojs.shiharr.com) ───────────────────────────────────
// Publishing entities on this platform:
//   1. SHIHARR PUBLISHING LIMITED (香港拾华出版有限公司) — China, Hong Kong SAR
//   2. China Architecture Culture Publishing House (中国建筑文化出版社) — China, Hong Kong SAR
export const SHIHARR_JOURNALS: Journal[] = [

  // ── SHIHARR PUBLISHING LIMITED ──────────────────────────────────────────

  {
    id: 'j-rwxk',
    journal_code: 'rwxk',
    title: '人文学刊',
    short_title: '人文学刊',
    issn_print: '3104-5014',
    issn_online: '3104-5022',
    publisher: 'SHIHARR PUBLISHING LIMITED',
    country: 'China, Hong Kong SAR',
    language: 'Chinese',
    frequency: 'Continuous',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/rwxk',
    cover_image_url: 'https://ojs.shiharr.com/public/journals/5/cover_issue_73_zh_Hans.png',
    oai_base_url: 'https://ojs.shiharr.com/index.php/rwxk/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 56,
    transparency_score: 68,
    indexing_readiness: 'B',
    pqf: pqf(17, 14, 12, 12, 5, 3),  // total: 63, Grade B
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

  {
    id: 'j-jyyjx',
    journal_code: 'jyyjx',
    title: '教育与教法',
    short_title: '教育与教法',
    issn_print: '3080-8839',
    issn_online: '3080-8847',
    publisher: 'SHIHARR PUBLISHING LIMITED',
    country: 'China, Hong Kong SAR',
    language: 'Chinese',
    frequency: 'Monthly',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/jyyjx',
    cover_image_url: 'https://ojs.shiharr.com/public/journals/3/cover_issue_77_zh_Hans.png',
    oai_base_url: 'https://ojs.shiharr.com/index.php/jyyjx/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 60,
    transparency_score: 64,
    indexing_readiness: 'B',
    pqf: pqf(16, 15, 12, 12, 5, 3),  // total: 63, Grade B
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

  {
    id: 'j-jassp',
    journal_code: 'jassp',
    title: 'Journal of Asia Social Science Practice',
    short_title: 'JASSP',
    issn_print: null,
    issn_online: '3079-7659',
    publisher: 'SHIHARR PUBLISHING LIMITED',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Continuous',
    open_access: true,
    license: 'Open Access',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/jassp',
    cover_image_url: 'https://ojs.shiharr.com/public/journals/1/cover_issue_54_en.png',
    oai_base_url: 'https://ojs.shiharr.com/index.php/jassp/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 68,
    transparency_score: 76,
    indexing_readiness: 'B',
    pqf: pqf(19, 17, 16, 13, 5, 4),  // total: 74, Grade B+
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

  {
    id: 'j-zgwxxk',
    journal_code: 'zgwxxk',
    title: '中国文学学刊',
    short_title: '中国文学学刊',
    issn_print: '3106-3667',
    issn_online: '3106-3675',
    publisher: 'SHIHARR PUBLISHING LIMITED',
    country: 'China, Hong Kong SAR',
    language: 'Chinese',
    frequency: 'Continuous',
    open_access: true,
    license: 'Open Access',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/zgwxxk',
    cover_image_url: 'https://ojs.shiharr.com/public/journals/14/cover_issue_32_zh_Hans.jpg',
    oai_base_url: 'https://ojs.shiharr.com/index.php/zgwxxk/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 52,
    transparency_score: 60,
    indexing_readiness: 'C',
    pqf: pqf(15, 13, 11, 11, 4, 3),  // total: 57, Grade C
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

  {
    id: 'j-yishu',
    journal_code: 'yishu',
    title: '艺术与设计前沿',
    short_title: '艺术与设计前沿',
    issn_print: '3107-0183',
    issn_online: '3107-0191',
    publisher: 'SHIHARR PUBLISHING LIMITED',
    country: 'China, Hong Kong SAR',
    language: 'Chinese',
    frequency: 'Continuous',
    open_access: true,
    license: 'Open Access',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/yishu',
    cover_image_url: 'https://ojs.shiharr.com/public/journals/16/cover_issue_47_zh_Hans.png',
    oai_base_url: 'https://ojs.shiharr.com/index.php/yishu/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 52,
    transparency_score: 60,
    indexing_readiness: 'C',
    pqf: pqf(15, 13, 10, 11, 4, 3),  // total: 56, Grade C
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

  {
    id: 'j-shr-ai',
    journal_code: 'shr-ai',
    title: '人工智能',
    short_title: '人工智能',
    issn_print: '3106-3691',
    issn_online: '3106-3705',
    publisher: 'SHIHARR PUBLISHING LIMITED',
    country: 'China, Hong Kong SAR',
    language: 'Chinese; English',
    frequency: 'Continuous',
    open_access: true,
    license: 'Open Access',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/ai',
    cover_image_url: 'https://ojs.shiharr.com/public/journals/11/cover_issue_17_zh_Hans.jpg',
    oai_base_url: 'https://ojs.shiharr.com/index.php/ai/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 52,
    transparency_score: 60,
    indexing_readiness: 'C',
    pqf: pqf(15, 13, 10, 11, 4, 3),  // total: 56, Grade C
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

  {
    id: 'j-smn',
    journal_code: 'smn',
    title: '医学与护理',
    short_title: '医学与护理',
    issn_print: '3106-3659',
    issn_online: '3106-3713',
    publisher: 'SHIHARR PUBLISHING LIMITED',
    country: 'China, Hong Kong SAR',
    language: 'Chinese; English',
    frequency: 'Continuous',
    open_access: true,
    license: 'Open Access',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/smn',
    cover_image_url: 'https://ojs.shiharr.com/public/journals/9/cover_issue_13_en.jpg',
    oai_base_url: 'https://ojs.shiharr.com/index.php/smn/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 52,
    transparency_score: 64,
    indexing_readiness: 'C',
    pqf: pqf(16, 13, 11, 11, 4, 4),  // total: 59, Grade C
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

  {
    id: 'j-xw',
    journal_code: 'xw',
    title: '新闻与传播',
    short_title: '新闻与传播',
    issn_print: null,
    issn_online: '3106-9983',
    publisher: 'SHIHARR PUBLISHING LIMITED',
    country: 'China, Hong Kong SAR',
    language: 'Chinese',
    frequency: 'Continuous',
    open_access: true,
    license: 'Open Access',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/xw',
    cover_image_url: 'https://ojs.shiharr.com/public/journals/10/cover_issue_15_zh_Hans.png',
    oai_base_url: 'https://ojs.shiharr.com/index.php/xw/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 52,
    transparency_score: 60,
    indexing_readiness: 'C',
    pqf: pqf(15, 13, 10, 11, 4, 3),  // total: 56, Grade C
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

  {
    id: 'j-zgfx',
    journal_code: 'zgfx',
    title: '中国法学学刊',
    short_title: '中国法学学刊',
    issn_print: '3107-1694',
    issn_online: '3107-1708',
    publisher: 'SHIHARR PUBLISHING LIMITED',
    country: 'China, Hong Kong SAR',
    language: 'Chinese',
    frequency: 'Continuous',
    open_access: true,
    license: 'Open Access',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/zgfx',
    cover_image_url: null,
    oai_base_url: 'https://ojs.shiharr.com/index.php/zgfx/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 52,
    transparency_score: 60,
    indexing_readiness: 'C',
    pqf: pqf(15, 13, 10, 11, 4, 3),  // total: 56, Grade C
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

  {
    id: 'j-cmas',
    journal_code: 'cmas',
    title: 'Engineering Frontiers',
    short_title: 'Eng. Frontiers',
    issn_print: '3105-4129',
    issn_online: '3106-0749',
    publisher: 'SHIHARR PUBLISHING LIMITED',
    country: 'China, Hong Kong SAR',
    language: 'English',
    frequency: 'Continuous',
    open_access: true,
    license: 'Open Access',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/cmas',
    cover_image_url: 'https://ojs.shiharr.com/public/journals/8/cover_issue_67_en.jpg',
    oai_base_url: 'https://ojs.shiharr.com/index.php/cmas/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 52,
    transparency_score: 64,
    indexing_readiness: 'C',
    pqf: pqf(16, 13, 10, 11, 4, 3),  // total: 57, Grade C — notable: no APC
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

  // ── China Architecture Culture Publishing House (中国建筑文化出版社) ──────

  {
    id: 'j-cds',
    journal_code: 'cds',
    title: '当代设计研究',
    short_title: '当代设计研究',
    issn_print: '3105-3807',
    issn_online: '3105-5834',
    publisher: 'China Architecture Culture Publishing House',
    country: 'China, Hong Kong SAR',
    language: 'Chinese',
    frequency: 'Continuous',
    open_access: true,
    license: 'Open Access',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/cds',
    cover_image_url: 'https://ojs.shiharr.com/public/journals/6/cover_issue_89_en.jpg',
    oai_base_url: 'https://ojs.shiharr.com/index.php/cds/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 44,
    transparency_score: 52,
    indexing_readiness: 'C',
    pqf: pqf(13, 11, 10, 10, 3, 3),  // total: 50, Grade C
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

  {
    id: 'j-rae',
    journal_code: 'rae',
    title: 'Research on Architecture and Environment',
    short_title: 'RAE',
    issn_print: '3105-319X',
    issn_online: '3105-5842',
    publisher: 'China Architecture Culture Publishing House',
    country: 'China, Hong Kong SAR',
    language: 'English; Chinese',
    frequency: 'Continuous',
    open_access: true,
    license: 'Open Access',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/rae',
    cover_image_url: 'https://ojs.shiharr.com/public/journals/7/cover_issue_82_zh_CN.jpg',
    oai_base_url: 'https://ojs.shiharr.com/index.php/rae/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 44,
    transparency_score: 52,
    indexing_readiness: 'C',
    pqf: pqf(13, 11, 9, 10, 3, 2),  // total: 48, Grade D
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

  {
    id: 'j-eaou',
    journal_code: 'eaou',
    title: 'Journal of the European Academy Open University',
    short_title: 'J. EAOU',
    issn_print: null,
    issn_online: '3105-5850',
    publisher: 'China Architecture Culture Publishing House; European Academy Open University',
    country: 'China, Hong Kong SAR',
    language: 'English; Chinese',
    frequency: 'Continuous',
    open_access: true,
    license: 'Open Access',
    peer_review_type: 'Peer review',
    website_url: 'https://ojs.shiharr.com/index.php/eaou',
    cover_image_url: 'https://ojs.shiharr.com/public/journals/12/cover_issue_86_en.png',
    oai_base_url: 'https://ojs.shiharr.com/index.php/eaou/oai',
    registration_country: 'China, Hong Kong SAR',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 36,
    transparency_score: 44,
    indexing_readiness: 'D',
    pqf: pqf(11, 9, 9, 9, 2, 2),  // total: 42, Grade D
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },

]

// ── Other Indexed Journals ────────────────────────────────────────────────
export const OTHER_INDEXED_JOURNALS: Journal[] = [
  {
    id: 'j-tjiss',
    journal_code: 'tjiss',
    title: 'The Journal of Interactive Social Sciences',
    short_title: 'TJISS',
    issn_print: '3030-5276',
    issn_online: '3030-5322',
    publisher: 'J&L Academic Group PLT',
    country: 'Malaysia',
    language: 'English',
    frequency: 'Quarterly',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://www.onlinejandl.com/index.php/TJISS',
    cover_image_url: 'https://www.onlinejandl.com/public/journals/3/cover_issue_6_en.jpg',
    oai_base_url: 'https://www.onlinejandl.com/index.php/TJISS/oai',
    registration_country: 'Malaysia',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 44,
    transparency_score: 60,
    indexing_readiness: 'C',
    pqf: pqf(15, 11, 8, 10, 3, 3),  // total: 50, Grade C
    article_count: 0,
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
]

export const ALL_JOURNALS: Journal[] = [...PSG_JOURNALS, ...INDEXED_JOURNALS, ...SHIHARR_JOURNALS, ...OTHER_INDEXED_JOURNALS]

// ISSN → journal_code lookup for mapping Crossref responses
export const ISSN_TO_CODE: Record<string, string> = Object.fromEntries(
  ALL_JOURNALS.filter(j => j.issn_online).map(j => [j.issn_online!, j.journal_code])
)

export function getJournalByCode(code: string): Journal | undefined {
  return ALL_JOURNALS.find(j => j.journal_code === code)
}

export function getJournalByIssn(issn: string): Journal | undefined {
  return ALL_JOURNALS.find(j => j.issn_online === issn || j.issn_print === issn)
}

export function getStats(liveArticleCount?: number): PlatformStats {
  const articles = liveArticleCount ?? ALL_JOURNALS.reduce((s, j) => s + j.article_count, 0)
  const doajListed = ALL_JOURNALS.filter(j => j.doaj_status === 'listed').length
  return {
    total_journals: ALL_JOURNALS.length,
    psg_journals: PSG_JOURNALS.length,
    indexed_journals: INDEXED_JOURNALS.length + SHIHARR_JOURNALS.length + OTHER_INDEXED_JOURNALS.length,
    total_articles: articles,
    total_authors: Math.round(articles * 2.6),
    total_doi_records: articles,
    crossref_verified: Math.round(articles * 0.85),
    openalex_matched: Math.round(articles * 0.3),
    doaj_listed: doajListed,
    open_citation_records: 0,
    avg_metadata_quality: Math.round(
      ALL_JOURNALS.reduce((s, j) => s + j.metadata_quality_score, 0) / ALL_JOURNALS.length
    ),
    last_updated: new Date().toISOString().slice(0, 10),
    data_version: '2.0',
  }
}
