import type { Journal, PqfScore, PlatformStats } from './types'

// PQF v1.0 formula: JTF/25 + MQF/25 + EGF/20 + TDF/15 + CVF/10 + RIF/5 = 100
function pqf(jtf: number, mqf: number, egf: number, tdf: number, cvf: number, rif: number): PqfScore {
  const total = jtf + mqf + egf + tdf + cvf + rif
  const grade =
    total >= 90 ? 'A+' :
    total >= 80 ? 'A'  :
    total >= 70 ? 'B+' :
    total >= 60 ? 'B'  :
    total >= 50 ? 'C'  :
    total >= 40 ? 'D'  : 'E'
  return {
    total,
    grade,
    subfactors: { jtf, mqf, egf, tdf, cvf, rif },
    evaluated_at: '2026-06-22',
    version: 'PQF v1.0',
  }
}

const COVER = (name: string) => `https://panorama-sg.com/QKFM/${name}.png`

// ── PSG Journals (12 journals published by Panorama Scholarly Group) ──────
export const PSG_JOURNALS: Journal[] = [
  {
    id: 'j-grhas',
    journal_code: 'grhas',
    title: 'Global Review of Humanities, Arts, and Society',
    short_title: 'GRHAS',
    issn_print: null,
    issn_online: '3052-539X',
    publisher: 'Panorama Scholarly Group',
    country: 'Hong Kong',
    language: 'English',
    frequency: 'Bimonthly',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/files',
    cover_image_url: COVER('GRAHS'),
    oai_base_url: 'https://journals.panorama-sg.com/index.php/files/oai',
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 72,
    transparency_score: 80,
    indexing_readiness: 'B',
    pqf: pqf(17, 18, 15, 10, 4, 2),  // total: 66, Grade B
    article_count: 24,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-aifs',
    journal_code: 'aifs',
    title: 'AI & Future Society',
    short_title: 'AI Fut. Soc.',
    issn_print: null,
    issn_online: '3053-4011',
    publisher: 'Panorama Scholarly Group',
    country: 'Hong Kong',
    language: 'English',
    frequency: 'Biannual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/aifs',
    cover_image_url: COVER('AFS'),
    oai_base_url: 'https://journals.panorama-sg.com/index.php/AFS/oai',
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 68,
    transparency_score: 75,
    indexing_readiness: 'B',
    pqf: pqf(15, 16, 14, 9, 3, 2),  // total: 59, Grade C
    article_count: 18,
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-jlpcs',
    journal_code: 'jlpcs',
    title: 'Journal of Law, Psychology, and Communication Studies',
    short_title: 'JLPCS',
    issn_print: null,
    issn_online: '3052-9654',
    publisher: 'Panorama Scholarly Group',
    country: 'Hong Kong',
    language: 'English; Chinese',
    frequency: 'Biannual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/jlpcs',
    cover_image_url: COVER('JLPCS'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 65,
    transparency_score: 70,
    indexing_readiness: 'C',
    pqf: pqf(13, 14, 12, 8, 3, 1),  // total: 51, Grade C
    article_count: 20,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-hnex',
    journal_code: 'hnex',
    title: 'Health Nexus: Interdisciplinary Medical Research Journal',
    short_title: 'Health Nexus',
    issn_print: null,
    issn_online: '3053-7037',
    publisher: 'Panorama Scholarly Group',
    country: 'Hong Kong',
    language: 'English',
    frequency: 'Annual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/hn',
    cover_image_url: COVER('HealthNexus'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 70,
    transparency_score: 73,
    indexing_readiness: 'C',
    pqf: pqf(14, 15, 13, 9, 3, 2),  // total: 56, Grade C
    article_count: 15,
    created_at: '2024-09-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-pear',
    journal_code: 'pear',
    title: 'PoliEcoM Administration Review',
    short_title: 'PEMR',
    issn_print: null,
    issn_online: '3053-3597',
    publisher: 'Panorama Scholarly Group',
    country: 'Hong Kong',
    language: 'English',
    frequency: 'Biannual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/pear',
    cover_image_url: COVER('REMR'),
    oai_base_url: 'https://journals.panorama-sg.com/index.php/pemr/oai',
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 60,
    transparency_score: 68,
    indexing_readiness: 'C',
    pqf: pqf(13, 13, 11, 8, 2, 1),  // total: 48, Grade D
    article_count: 12,
    created_at: '2024-09-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-jesa',
    journal_code: 'jesa',
    title: 'Journal of Engineering Systems and Applications',
    short_title: 'JESA',
    issn_print: null,
    issn_online: '3053-478X',
    publisher: 'Panorama Scholarly Group',
    country: 'Hong Kong',
    language: 'English',
    frequency: 'Annual',
    open_access: true,
    license: 'CC BY-NC 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/jesa',
    cover_image_url: COVER('JESA'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 65,
    transparency_score: 70,
    indexing_readiness: 'C',
    pqf: pqf(13, 14, 12, 8, 3, 1),  // total: 51, Grade C
    article_count: 11,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-tts',
    journal_code: 'tts',
    title: 'Three Teachings Studies: Confucianism, Daoism, and Buddhism',
    short_title: 'TTS',
    issn_print: null,
    issn_online: '3053-6553',
    publisher: 'Panorama Scholarly Group',
    country: 'Hong Kong',
    language: 'English; Chinese; Japanese; Korean; Vietnamese',
    frequency: 'Annual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/tts',
    cover_image_url: COVER('TTS'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'application_submitted',
    openalex_source_id: null,
    metadata_quality_score: 60,
    transparency_score: 65,
    indexing_readiness: 'C',
    pqf: pqf(12, 15, 12, 11, 0, 2),  // total: 52, Grade C
    article_count: 8,
    created_at: '2024-12-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-rggd',
    journal_code: 'rggd',
    title: 'Rural Governance and Green Development',
    short_title: 'RGGD',
    issn_print: null,
    issn_online: '3053-7282',
    publisher: 'Panorama Scholarly Group',
    country: 'Hong Kong',
    language: 'English',
    frequency: 'Annual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/rggd',
    cover_image_url: COVER('RGGD'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 55,
    transparency_score: 62,
    indexing_readiness: 'D',
    pqf: pqf(11, 11, 10, 7, 2, 1),  // total: 42, Grade D
    article_count: 8,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-rjgms',
    journal_code: 'rjgms',
    title: 'Resonance: Journal of Global Music Studies',
    short_title: 'Resonance',
    issn_print: null,
    issn_online: '3053-4410',
    publisher: 'Panorama Scholarly Group',
    country: 'Hong Kong',
    language: 'English; Chinese; German; Italian; Russian',
    frequency: 'Biannual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/Resonance',
    cover_image_url: COVER('RESONANCE'),
    oai_base_url: 'https://journals.panorama-sg.com/index.php/Resonance/oai',
    registration_country: 'Germany',
    doaj_status: 'application_submitted',
    openalex_source_id: 'S5407051440',
    metadata_quality_score: 63,
    transparency_score: 70,
    indexing_readiness: 'B',
    pqf: pqf(15, 15, 14, 12, 2, 2),  // total: 60, Grade B
    article_count: 14,
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-csgs',
    journal_code: 'csgs',
    title: 'Climate Sustainability & Global Systems',
    short_title: 'CSGS',
    issn_print: null,
    issn_online: '3054-9663',
    publisher: 'Panorama Scholarly Group',
    country: 'Hong Kong',
    language: 'English',
    frequency: 'Quarterly',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/csgs',
    cover_image_url: COVER('CSGS'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 55,
    transparency_score: 62,
    indexing_readiness: 'D',
    pqf: pqf(11, 11, 10, 7, 2, 1),  // total: 42, Grade D
    article_count: 6,
    created_at: '2025-06-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-jscc',
    journal_code: 'jscc',
    title: 'Journal of Social Cognition and Communication',
    short_title: 'JSCC',
    issn_print: null,
    issn_online: '3054-6958',
    publisher: 'Panorama Scholarly Group',
    country: 'Hong Kong',
    language: 'English',
    frequency: 'Biannual',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/jscc',
    cover_image_url: COVER('JSCC'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 58,
    transparency_score: 64,
    indexing_readiness: 'C',
    pqf: pqf(12, 12, 11, 7, 2, 1),  // total: 45, Grade D
    article_count: 10,
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-silence',
    journal_code: 'silence',
    title: 'Silence',
    short_title: 'Silence',
    issn_print: null,
    issn_online: '3054-4386',
    publisher: 'Panorama Scholarly Group',
    country: 'Hong Kong',
    language: 'English',
    frequency: 'Irregular',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://journals.panorama-sg.com/index.php/Silence',
    cover_image_url: COVER('Silence'),
    oai_base_url: null,
    registration_country: 'Germany',
    doaj_status: 'not_listed',
    openalex_source_id: null,
    metadata_quality_score: 52,
    transparency_score: 60,
    indexing_readiness: 'D',
    pqf: pqf(10, 10, 10, 7, 2, 1),  // total: 40, Grade D
    article_count: 5,
    created_at: '2025-06-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
]

// ── Indexed Journals (third-party publishers indexed by POSI) ─────────────
export const INDEXED_JOURNALS: Journal[] = [
  {
    id: 'j-jmss',
    journal_code: 'jmss',
    title: 'Journal of Modern Social Sciences',
    short_title: 'JMSS',
    issn_print: '3078-4433',
    issn_online: '3078-4441',
    publisher: 'Asia Technology Research Institute',
    country: 'Hong Kong',
    language: 'English',
    frequency: 'Continuous',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://atripress.org/index.php/jmss',
    cover_image_url: 'https://atripress.org/public/journals/1/cover_issue_5_en_US.jpg',
    oai_base_url: null,
    registration_country: 'China',
    doaj_status: null,
    openalex_source_id: null,
    metadata_quality_score: 60,
    transparency_score: 65,
    indexing_readiness: 'C',
    pqf: pqf(17, 14, 11, 10, 2, 2),  // total: 56, Grade C
    article_count: 0,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-jcsis',
    journal_code: 'jcsis',
    title: 'Journal of Current Social Issues Studies',
    short_title: 'JCSIS',
    issn_print: '3078-5316',
    issn_online: '3078-5324',
    publisher: 'Asia Technology Research Institute',
    country: 'Hong Kong',
    language: 'English',
    frequency: 'Continuous',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://atripress.org/index.php/jcsis',
    cover_image_url: 'https://atripress.org/public/journals/2/cover_issue_6_en_US.jpg',
    oai_base_url: null,
    registration_country: 'China',
    doaj_status: null,
    openalex_source_id: null,
    metadata_quality_score: 63,
    transparency_score: 68,
    indexing_readiness: 'B',
    pqf: pqf(18, 15, 14, 10, 2, 2),  // total: 61, Grade B
    article_count: 0,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'j-jcac',
    journal_code: 'jcac',
    title: 'Journal of Contemporary Art Criticism',
    short_title: 'JCAC',
    issn_print: '3079-7470',
    issn_online: '3079-7489',
    publisher: 'Asia Technology Research Institute',
    country: 'Hong Kong',
    language: 'English',
    frequency: 'Continuous',
    open_access: true,
    license: 'CC BY 4.0',
    peer_review_type: 'Double-blind',
    website_url: 'https://atripress.org/index.php/jcac',
    cover_image_url: 'https://atripress.org/public/journals/4/cover_issue_9_en_US.jpg',
    oai_base_url: null,
    registration_country: null,
    doaj_status: null,
    openalex_source_id: null,
    metadata_quality_score: 58,
    transparency_score: 63,
    indexing_readiness: 'C',
    pqf: pqf(14, 12, 10, 9, 2, 1),  // total: 48, Grade D
    article_count: 0,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
]

export const ALL_JOURNALS: Journal[] = [...PSG_JOURNALS, ...INDEXED_JOURNALS]

// ISSN → journal_code lookup for mapping Crossref responses
export const ISSN_TO_CODE: Record<string, string> = Object.fromEntries(
  ALL_JOURNALS.filter(j => j.issn_online).map(j => [j.issn_online!, j.journal_code])
)

export function getJournalByCode(code: string): Journal | undefined {
  return ALL_JOURNALS.find(j => j.journal_code === code)
}

export function getJournalByIssn(issn: string): Journal | undefined {
  return ALL_JOURNALS.find(j => j.issn_online === issn || j.issn_print === issn)
}

export function getStats(liveArticleCount?: number): PlatformStats {
  const articles = liveArticleCount ?? ALL_JOURNALS.reduce((s, j) => s + j.article_count, 0)
  const doajListed = ALL_JOURNALS.filter(j => j.doaj_status === 'listed').length
  return {
    total_journals: ALL_JOURNALS.length,
    psg_journals: PSG_JOURNALS.length,
    indexed_journals: INDEXED_JOURNALS.length,
    total_articles: articles,
    total_authors: Math.round(articles * 2.6),
    total_doi_records: articles,
    crossref_verified: Math.round(articles * 0.85),
    openalex_matched: Math.round(articles * 0.3),
    doaj_listed: doajListed,
    open_citation_records: 0,
    avg_metadata_quality: Math.round(
      ALL_JOURNALS.reduce((s, j) => s + j.metadata_quality_score, 0) / ALL_JOURNALS.length
    ),
    last_updated: '2026-06-22',
    data_version: '2.0',
  }
}
