// Generated by scripts/gen-locale-routes.mjs; do not edit.
// Re-exports src/app/certificate/zone/page.tsx under each language prefix.
export { default, metadata } from '@/app/certificate/zone/page'
