// Generated by scripts/gen-locale-routes.mjs; do not edit.
// Re-exports src/app/(docs)/docs/schema/page.tsx under each language prefix.
export { default, metadata } from '@/app/(docs)/docs/schema/page'
