// Generated by scripts/gen-locale-routes.mjs; do not edit.
// Re-exports src/app/rankings/edition/[year]/page.tsx under each language prefix.
export { default, generateMetadata, generateStaticParams } from '@/app/rankings/edition/[year]/page'
export const dynamicParams = false
