// Generated by scripts/gen-locale-routes.mjs; do not edit.
// Re-exports src/app/journals/open-access/page.tsx under each language prefix.
export { default, metadata } from '@/app/journals/open-access/page'
