// Interface languages.
//
// Every page has an address in each language: English is unprefixed (/),
// the others sit under a prefix (/ja/, /ko/, /zh-cn/, /zh-tw/), the same
// contract as the Panorama Scholarly Group homepage. The prefixed copies
// are thin route files generated by scripts/gen-locale-routes.mjs.
//
// Two exceptions keep the static export inside Cloudflare Pages' file
// limit: the per-record pages (journal records, publisher pages, archived
// ranking editions, ~1,500 pages) exist once, unprefixed. On those, the
// interface follows the reader's saved language.
//
// What is translated is the interface (navigation, search, footer, the
// home page). Record data (titles, publishers, subjects) stays as
// published by its source, and pages whose body is not yet translated
// keep their English canonical address.
//
// Messages are keyed by the English source text, so an untranslated string
// simply falls back to English.

import ja from './messages/ja.ts'
import ko from './messages/ko.ts'
import zhHans from './messages/zh-Hans.ts'
import zhHant from './messages/zh-Hant.ts'

// path: the URL prefix. lang: <html lang>, which also picks the CJK fonts
// in globals.css. hreflang: the alternate-language tag for search engines.
export const LOCALES = [
  { code: 'en', label: 'English', path: '', lang: 'en', hreflang: 'en', og: 'en_US' },
  { code: 'ja', label: '日本語', path: 'ja', lang: 'ja', hreflang: 'ja', og: 'ja_JP' },
  { code: 'ko', label: '한국어', path: 'ko', lang: 'ko', hreflang: 'ko', og: 'ko_KR' },
  { code: 'zh-Hans', label: '简体中文', path: 'zh-cn', lang: 'zh-CN', hreflang: 'zh-Hans', og: 'zh_CN' },
  { code: 'zh-Hant', label: '繁體中文', path: 'zh-tw', lang: 'zh-TW', hreflang: 'zh-Hant', og: 'zh_TW' },
] as const

export type Locale = typeof LOCALES[number]['code']
export type Messages = Record<string, string>

export const DEFAULT_LOCALE: Locale = 'en'
export const LOCALE_STORAGE_KEY = 'posi-locale'

const MESSAGES: Record<Locale, Messages> = { en: {}, ja, ko, 'zh-Hans': zhHans, 'zh-Hant': zhHant }

export function isLocale(v: unknown): v is Locale {
  return LOCALES.some(l => l.code === v)
}

/** Translate an English source string; `{name}` placeholders are filled from `vars`. */
export function translate(locale: Locale, text: string, vars?: Record<string, string | number>): string {
  let out = MESSAGES[locale][text] ?? text
  if (vars) for (const [k, v] of Object.entries(vars)) out = out.replaceAll(`{${k}}`, String(v))
  return out
}

export type LocaleInfo = typeof LOCALES[number]

export function localeInfo(locale: Locale): LocaleInfo {
  return LOCALES.find(l => l.code === locale)!
}

/** The BCP 47 tag for <html lang>. */
export function htmlLang(locale: Locale): string {
  return localeInfo(locale).lang
}

/** The prefixed locales, as the [locale] route segment spells them. */
export const LOCALE_PATHS = LOCALES.filter(l => l.path).map(l => l.path)

/** The locale a URL prefix names ("zh-cn" -> zh-Hans), or null for none. */
export function localeFromSegment(segment: string | undefined): Locale | null {
  const l = LOCALES.find(x => x.path && x.path === segment?.toLowerCase())
  return l ? l.code : null
}

/** The locale an address belongs to, from its first path segment. */
export function localeFromPath(pathname: string): Locale | null {
  return localeFromSegment(pathname.split('/')[1])
}

/** Strip a language prefix: '/zh-cn/about/' -> '/about/'. */
export function unlocalizedPath(pathname: string): string {
  return localeFromPath(pathname) ? pathname.replace(/^\/[^/]+/, '') || '/' : pathname
}

/**
 * Addresses with no prefixed copy (see the note at the top). Keep in step
 * with EXCLUDED in scripts/gen-locale-routes.mjs; locales.test.ts checks.
 */
export const UNLOCALIZED_PATTERNS = [
  '^/journal/[^/]+/',              // journal records
  '^/publishers/[^/]+/',           // publisher pages
  '^/rankings/edition/[^/]+/[^/]+/', // archived ranking editions, by category
  '^/(data|api|_next)/',           // data files and assets
  '\\.[A-Za-z0-9]+$',            // files
]
const UNLOCALIZED = UNLOCALIZED_PATTERNS.map(p => new RegExp(p))

/** Whether an (unprefixed) path has a copy under each language prefix. */
export function hasLocalizedCopy(path: string): boolean {
  return !UNLOCALIZED.some(r => r.test(path))
}

/**
 * An internal href in a language: localizeHref('/about/?x=1', 'ja') ->
 * '/ja/about/?x=1'. Already-prefixed hrefs are re-prefixed; external hrefs,
 * and paths with no localized copy, are returned unchanged.
 */
export function localizeHref(href: string, locale: Locale): string {
  if (!href.startsWith('/') || href.startsWith('//')) return href
  const cut = href.search(/[?#]/)
  const path = unlocalizedPath(cut < 0 ? href : href.slice(0, cut))
  const rest = cut < 0 ? '' : href.slice(cut)
  const { path: prefix } = localeInfo(locale)
  return prefix && hasLocalizedCopy(path) ? `/${prefix}${path}${rest}` : `${path}${rest}`
}

/**
 * Pages whose content (not only the interface) is translated. They are
 * their own canonical address in each language and are listed with
 * hreflang alternates; the other prefixed copies point to the English page
 * as canonical.
 */
export const TRANSLATED_PAGES = ['/']

/** A page's address in a language: localizedPath('/', 'ja') -> '/ja/'. */
export function localizedPath(page: string, locale: Locale): string {
  return localizeHref(page, locale)
}
