// Generated by scripts/gen-locale-routes.mjs; do not edit.
// Re-exports src/app/(docs)/ratings/mature/page.tsx under each language prefix.
export { default, metadata } from '@/app/(docs)/ratings/mature/page'
