// Generated by scripts/gen-locale-routes.mjs; do not edit.
// Re-exports src/app/journals/subject/[code]/page.tsx under each language prefix.
export { default, generateMetadata, generateStaticParams } from '@/app/journals/subject/[code]/page'
export const dynamicParams = false
