import { LOCALE_PATHS } from '@/lib/i18n/locales'

// Every page under each language prefix: /ja/, /ko/, /zh-cn/, /zh-tw/.
// The pages below are thin copies generated by scripts/gen-locale-routes.mjs;
// the language itself comes from the address (see components/I18n.tsx).
export const dynamicParams = false

export function generateStaticParams() {
  return LOCALE_PATHS.map(locale => ({ locale }))
}

export default function LocaleLayout({ children }: { children: React.ReactNode }) {
  return children
}
