// Generated by scripts/gen-locale-routes.mjs; do not edit.
// Re-exports src/app/(docs)/announcements/[slug]/page.tsx under each language prefix.
export { default, generateMetadata, generateStaticParams } from '@/app/(docs)/announcements/[slug]/page'
export const dynamicParams = false
